# Generated by Django 6.0.3 on 2026-03-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table_sessions', '0002_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpagerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffpagerequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_page_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffpagerequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_requests', to='table_sessions.tablesession'),
        ),
        migrations.AddField(
            model_name='staffpagerequest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_requests', to='tables.table'),
        ),
        migrations.AddField(
            model_name='tablemergegroup',
            name='tables',
            field=models.ManyToManyField(related_name='merge_groups', to='tables.table'),
        ),
        migrations.AddField(
            model_name='tablescanrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablescanrequest',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_requests', to='tables.table'),
        ),
    ]
