# Generated by Django 6.0.3 on 2026-03-19 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placed_by_name', models.CharField(blank=True, max_length=120, null=True)),
                ('placed_by_role', models.CharField(blank=True, max_length=30, null=True)),
                ('placed_for_name', models.CharField(blank=True, max_length=120, null=True)),
                ('placed_for_contact', models.CharField(blank=True, max_length=120, null=True)),
                ('channel', models.CharField(choices=[('customer_account', 'Customer Account'), ('guest', 'Guest'), ('waiter_assisted', 'Waiter Assisted'), ('bulk', 'Bulk'), ('pos_sync', 'POS Sync')], default='customer_account', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('kitchen_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('not_required', 'Not Required'), ('awaiting_verification', 'Awaiting Verification')], default='pending', max_length=30)),
                ('bar_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('not_required', 'Not Required'), ('awaiting_verification', 'Awaiting Verification')], default='pending', max_length=30)),
                ('cashier_status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('not_required', 'Not Required'), ('awaiting_verification', 'Awaiting Verification')], default='pending', max_length=30)),
                ('is_bulk_order', models.BooleanField(default=False)),
                ('requires_cashier_verification', models.BooleanField(default=False)),
                ('price_alert_sent', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('external_pos_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('inventory_committed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('station', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customization_notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=40)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
