# Generated by Django 5.2.7 on 2026-03-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('table_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_sessions.tablesession'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
