# Generated by Django 6.0.3 on 2026-03-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaylist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderplaylistitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='orderplaylistitem',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.orderplaylist'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='orderplaylist',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='orderplaylistitem',
            unique_together={('playlist', 'menu_item')},
        ),
    ]
